### ISSUE TITLE
Options for a template are not showing when `--help` is passed

### ISSUE THREAD

**Issue by meddle0x53** [pragdave/mix_generator#1]
So I installed the `mix_generator` and `mix_templates` mixtures.
Then installed the `project` template:

```
mix gen --list

Locally installed templates:
project:
        Simple template for projects (with optional app and supervision)
```

Even made a little project - worked just fine.

Tried to see the available options as per the `README.md` documentation with `mix gen project --help`.

I get

```
ERROR: missing name of project
```

It doesn't parse the `--help` option. By the way `mix template project --help` doesn't work either.

**Comment by pragdave** [comment]
I guess it would have worked better if I'd implemented it :)

Should be good now.

Thanks for the report.



Dave
